SliverFlexibleHeader proposal
Kavantix/sliver_tools pull request #66
Opened 2022-10-22 10:41 UTC by marcoredz

2022-12-04 09:47 UTC, jascodes commented
@Kavantix Whats holding this back?

2022-12-04 09:59 UTC, jascodes commented
@marcoredz Doesn't work in Sliver Stack btw

cc @Kavantix

2023-02-01 19:48 UTC, Kavantix commented
@marcoredz sorry for the late reply, have been swamped again.
But thanks for the contribution!
In general the implementation looks good although I'm not sure if it handles the overlap correctly in all cases.
Could you add some tests for a few simple cases and some overlap cases.

For the API of the package it would make more sense to have a `SliverFloatingHeader` widget that is always floating since there is already a `SliverPinnedHeader`

2023-02-01 19:48 UTC, Kavantix requested changes
Could you add some tests for a few simple cases and some overlap cases.

For the API of the package it would make more sense to have a SliverFloatingHeader widget that is always floating since there is already a SliverPinnedHeader

2023-06-13 13:38 UTC, marcoredz commented
Apologies for the delayed response, @Kavantix. My proposal was based on this gist: https://gist.github.com/tomaszpolanski/cf0edb7961d2304c2f293da9971cd4c9. 

Unfortunately, I am currently unable to proceed with working on this proposal. Therefore, if you or someone else can find a way to incorporate this feature into the package, it would be awesome. Otherwise, it's not a problem for me if you decide to close the PR

2024-06-01 18:25 UTC, Kavantix commented
Closing since I also don’t have time for this right now, if anyone wants to pick it up let me know

2024-06-01 18:25 UTC, closed without merging